name: Install and use CLI

on: [push, pull_request]

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Install CLI
        uses: scaleway/action-scw@v0
        with:
          version: v2.14.0
      - run: scw instance server start --wait ${{ env.SERVER_ID }}
        env:
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          SCW_DEFAULT_PROJECT_ID: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
          SCW_DEFAULT_ORGANIZATION_ID: ${{ secrets.SCW_DEFAULT_ORGANIZATION_ID }}
